### ISSUE TITLE
v1.1.0 has no compiled JS files

### ISSUE THREAD

**Issue by noomorph** [stevenhair/lcov-badge2#308]
I hate to bring bad news, but you seem not to compile your package before publishing to npm.
Please react quickly.

🤷‍♂️

**Comment by noomorph** [comment]
@stevenhair please check `npm pack lcov-badge2` and see for yourself that there are no compiled JS files there inside.

**Comment by stevenhair** [comment]
Apologies, this has been fixed in v1.1.1. Thanks for letting me know.
